# This is a sample aws-auth-patch.yml file. 
# Actual aws-auth-patch.yml will be created at /System/Volumes/Data/private/tmp/aws-auth-patch.yml path.

apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::473279402447:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-16YJPHE80E4FT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::473279402447:role/UdacityFlaskDeployCBKubectlRole
      username: build      
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-29T19:22:59Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1694"
  uid: bd3222b7-97f0-4689-9182-4c6007e4acae
